// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fblzswyxvhlfkbosxfsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZibHpzd3l4dmhsZmtib3N4ZnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzYyNzIsImV4cCI6MjA2NDQxMjI3Mn0.82dnSvUMaVW3FkmveZD771_cptrbBEratSwbnDw6zvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);